[package]
name = "rzfs_userspace"
version = "0.0.0"
edition = "2021"
description = "Rust userspace tool for parsing ZFS data structures."
license = "GPL-2.0+ OR MIT"

[[bin]]
name = "rzfs"

[dependencies]
rzfs_lib = { "version" = "0.0.0" }
